quarkus:
  application:
    name: jogadores-service
  http:
    port: 8001
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5448/eati_jogadores
  flyway:
    migrate-at-start: true
    schemas: jogadores
