insert into jogadores.jogadores (nome, time, camisa) values
('Sergio Rochet', 'Internacional', 33),
('Gabriel Mercado', 'Internacional', 25),
('Igor Gomes', 'Internacional', 21),
('Nico Hernández', 'Internacional', 22),
('Rodrigo Moledo', 'Internacional', 4),
('Vitão', 'Internacional', 44),
('Dalbert', 'Internacional', 29),
('Fabricio Bustos', 'Internacional', 16),
('Hugo Mallo', 'Internacional', 2),
('Renê', 'Internacional', 6),
('Alan Patrick', 'Internacional', 10),
('Bruno Henrique', 'Internacional', 8),
('Thauan Lara', 'Internacional', 36),
('Carlos de Pena', 'Internacional', 14),
('Charles Aránguiz', 'Internacional', 20),
('Estêvão', 'Internacional', 26),
('Gabriel', 'Internacional', 23),
('Gustavo Campanharo', 'Internacional', 17),
('Johnny', 'Internacional', 30),
('Lucas Ramos', 'Internacional', 15),
('Mauricio', 'Internacional', 27),
('Matheus Dias', 'Internacional', 41),
('Rômulo', 'Internacional', 40),
('Enner Valencia', 'Internacional', 13),
('Gabriel Barros', 'Internacional', 42),
('Jean Dias', 'Internacional', 38),
('Lucca', 'Internacional', 45),
('Luiz Adriano', 'Internacional', 9),
('Pedro Henrique', 'Internacional', 28),
('Wanderson', 'Internacional', 11);
