quarkus:
  application:
    name: apuracao-service
  http:
    port: 8003
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5448/eati_apuracao
  flyway:
    migrate-at-start: true
    schemas: apuracao
kafka:
  bootstrap:
    servers:  localhost:29092
  auto:
    offset:
      reset: earliest
clients:
  jogadores/mp-rest/url: http://localhost:8001
  jogadores/mp-rest/scope: javax.inject.Singleton
#mp:
#  messaging:
#    incoming:
#      voto-computado:
#        connector: smallrye-kafka
#        commit-strategy: latest
